# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: ezekiel342007@gmail.com
author_name: ezekiel342007
cloud_provider: none
contract_name: algohub
deployment_language: python
preset_name: production
project_name: algohub

