# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ezekiel342007@gmail.com
author_name: ezekiel342007
contract_name: algohub
deployment_language: python
preset_name: production
project_name: algohub-contracts

